src/food/urls.py
from django.urls import path
from .views import *

app_name = 'food'
urlpatterns = [
    path('', index, name='index'),
    path('item/', item, name='item'),
    path('<int:item_id>/', detail, name='detail'),
    path('add', create_item, name='create_item'),
    path('update/<int:id>', update_item, name='update_item'),
    path('delete/<int:id>', delete_item, name='delete_item')
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include   
from users import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

src/food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJtIrj6mXG4Dwt-eacKnB77UfKihG2cX05Zw&s')

src/users/models.py
from django.db import models

# Create your models here.

src/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

src/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from .models import Item
from .forms import ItemForm

def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list' : item_list,
    }
    return render(request, 'index.html', context)


def item(request):
    return HttpResponse('This is an item view.')

def detail(request, item_id):
    item = Item.objects.get(id=item_id)
    context = {
        'item': item,
    }
    return render(request, 'detail.html', context)


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'item-form.html',{'form':form})

def update_item(request, id):
    item = Item.objects.get(id = id)

    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'item-form.html',{'form':form, 'item':item})

def delete_item(request, id):
    item = Item.objects.get(id = id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'item-delete.html', {'item':item})

src/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm

def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account is created')
            return redirect('login')

    else:
        form = RegisterForm()

    return render(request, 'register.html', {'form':form})

src/food/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    {% include 'navbar.html' %}

    {% if messages %}

        {% for m in messages %}
        <div class="alert alert-{{ m.tags }}">
            {{ m }}

        </div>
        
        {% endfor %}
    {% endif %}


    {% block content %}
    
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

src/food/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_image }}" class="card" width="300px" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>$ {{ item.item_price }}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>

</body>
</html>


{% endblock %}

src/food/templates/index.html
{% extends 'base.html' %}

{% block content %}




    {% for item in item_list %}
<div class="container p-3 mt-2">

    
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img src="{{ item.item_image }}" class="card" width="150px">
        </div>
        <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_desc }}</h5>
            <h6>{{ item.item_price }}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
</div>

    {% endfor %}


{% endblock %}

src/food/templates/item-delete.html
<form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

src/food/templates/item-form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">

            <form method="POST">
                {% csrf_token %}
                {{ form }}
            
                <button type="submit">Save</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

src/food/templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Food App</a>

    <div class="navbar">
        <a href="{% url 'food:create_item' %}" class="nav-item p-2">Add Item</a>
        <a href="#" class="nav-item p-2">Delete Item</a>
        <a href="#" class="nav-item p-2">View Item</a>
    </div>
</nav>

src/users/templates/login.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

src/users/templates/logout.html
<h2>You are logged out</h2>

src/users/templates/register.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>